### ISSUE TITLE
General github style

### ISSUE THREAD

**Issue by RingOfStorms** [kryptonics/SadeikFinalProject#7]
This isn't really an issue for the project as they never told us anything against it but in the future your github repo shold only contain source fils and header files generally speaking. That means only the src/include folders and not the bin or obj folders, nor all of the IDE specific files that codeblocks generates.

The reason for not including all of those things is so that other people can easily fork and work with your project without a lot of bloat that they may not use (like if they had a different IDE). Likewise extra files and system files can easily be changed between computers and committers and will sometimes cause unknown code commit conflicts that don't actually matter to the project.

You can achieve not including these by creating a .gitignore file, I would recommend reading up on them for future projects.

Also, because you compiled this on linux, the executable we are runnign in the unix terminal wil 100% not work on windows. You have to compile for each target platform. This is another reason not to include a bin folder in your repo. If you want to include the executable file you can manually make a file in the downloads section of your repo on github!

PS> I accidentally made issues on the project for the other project that I was reviewing, I closed them. Sorry for that.

**Comment by kryptonics** [comment]
Ah I see! I did not know about any of these conventions so thank you so much for pointing this out! I would bet that this is why others are unable to get any encryption keys to work, including one I tested locally. Ill try excluding all the extraneous trunk junk files in my next commit and see if that solves some of the issues.
